name: Generate Keystore
on:
  workflow_dispatch: # این یعنی فقط وقتی خودمان بخواهیم اجرا شود

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -storepass 123456 -keypass 123456 -dname "CN=NakhAI, OU=Dev, O=NakhAI, L=City, S=State, C=IR"
      
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-key
          path: my-release-key.jks
